name: Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add .env
        run: echo -e "${{ secrets.ENV }}" > .env
      - name: Build Images
        run: docker-compose build
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Add .env
  #       run: echo -e "${{ secrets.ENV }}" > .env
  #     - name: Run tests
  #       run: docker-compose run --rm front yarn test
  deploy:
    # needs: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ github.repository }} 
            docker-compose down 
            git pull 
            echo -e "${{ secrets.ENV }}" > .env 
            docker-compose up -d --build --force-recreate

